language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

script: "mvn clean package"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp target/*.war before-deploy/
  - cp appspec.yml before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/mediaai-webservice.zip


deploy:
 - provider: s3
   access_key_id: AKIASTMUXDJ7PXOCRPFZ
   secret_access_key: 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 
   bucket: mediaai-build
   region: ap-northeast-2
   skip_cleanup: ture
   acl: private
   local_dir: deploy
   wait-util-deployed: true
 - provider: codedeploy
   access_key_id: AKIASTMUXDJ7PXOCRPFZ
   secret_access_key: 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 
   bucket: mediaai-build
   key: mediaai-webservice.zip
   bundle_type: zip
   application: mediaai-webservice
   deployment_group: mediaai-webservice-group
   region: ap-northeast-2
   wait-util-deployed: true

notification:
  email:
    recipients:
      - jisoobyun@aifactory.page
