language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

script: "mvn clean package"



before_deploy:
  - zip -r mediaai-webservice *
  - mkdir -p deploy
  - mv mediaai-webservice.zip deploy/mediaai-webservice.zip

deploy:
 - provider: s3
   access_key_id: AKIASTMUXDJ7PXOCRPFZ
   secret_access_key: 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 
   bucket: mediaai-build
   region: ap-northeast-2
   skip_cleanup: ture
   acl: private
   local_dir: deploy
   wait-util-deployed: true
 - provider: codedeploy
   access_key_id:
   secret_access_key:
   bucket: mediaai-build
   key: mediaai-webservice.zip
   bundle_type: zip
   application: mediaai-webservice
   deployment_group: mediaai-webservice-group
   region: ap-northeast-2
   wait-util-deployed: true

notification:
  email:
    recipients:
      - jisoobyun@aifactory.page